server:
  port: 9002

spring:
  application:
    name: account
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope:
              - email
              - profile
          facebook:
            client-id: id
            client-secret: secret
            scope:
              - email
              - public_profile

whitelist:
  paths:
    - /
    - /accounts
    - /account/*

hashids:
  salt: J5%pN84xi5MZ