server:
  port: 9999

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope:
              - email
              - profile
          facebook:
            client-id: id
            client-secret: secret
            scope:
              - email
              - public_profile

mybatis:
  configuration:
    map-underscore-to-camel-case: true

whitelist:
  paths:
    - /
    - /index

hashids:
  salt: J5%pN84xi5MZ