spring:
  http:
    log-request-details: true
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss:SSS'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    deserialization:
      fail-on-ignored-properties: false
  messages:
    basename: i18n/messages
  profiles:
    active: development
  threads:
    virtual:
      enabled: true

mybatis:
  type-handlers-package: com.tsinsi.foundation.JsonTypeHandler

logging:
  file:
    path: ./logs