spring:
  data:
    redis:
      port: 6379
      password: FlM34FN&peIc
      host: 127.0.0.1
      timeout: 30s
  datasource:
    writer:
      username: writer
      password: dbforstudy
      jdbc-url: jdbc:mysql://127.0.0.1:3306/study
      driver-class-name: com.mysql.cj.jdbc.Driver
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    reader:
      username: reader
      password: dbforstudy
      jdbc-url: jdbc:mysql://127.0.0.1:3306/study
      driver-class-name: com.mysql.cj.jdbc.Driver
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  devtools:
    add-properties: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    ch.qos.logback: ERROR
    com.zaxxer.hikari: DEBUG

sqids:
  alphabet: lHyvdsuj65rYFWpT2CBfRbUhKDGxJAzQaZ47XSc0VgPImtk8o3nwEq1NMe9OiL