spring:
  config:
    import:
      - optional:classpath:application-dev.yml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.tsinsi.user: DEBUG