server:
  port: 9002

spring:
  config:
    import:
      - classpath:base.yml
  application:
    name: account
  profiles:
    active: development

mybatis:
  type-handlers-package: com.tsinsi.user.configuration.JsonTypeHandler