= Auth API
Deppan;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: Account API
:toclevels: 1
:sectlinks:

[[overview]]
= Overview

include::common.adoc[]

[[overview_errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object that describes the problem.
The error object has the following structure:

For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:

[[overview_hypermedia]]
== Hypermedia

RESTful Notes uses hypermedia and resources include links to other resources in their responses.
Responses are in https://github.com/mikekelly/hal_specification[Hypertext
Application Language (HAL)] format.
Links can be found beneath the `_links` key.
Users of the API should not create URIs themselves, instead they should use the above-described links to navigate from resource to resource.

[[resources]]
= Resources

[[resources_auth]]
== Auth

[[resources_login]]
=== Login

A `GET` request will list all the service's accounts.

operation::login[]
