server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${auth.uri}
          predicates:
            - Path=/login
        - id: account
          uri: ${account.uri}
          predicates:
            - Path=/users/**, /user/**
hashids:
  salt: J5%pN84xi5MZ

whitelist:
  paths:
    - /login