server:
  port: 9000

spring:
  application:
    name: gateway
  profiles:
    active: development
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${auth.uri}
          predicates:
            - Path=/sign-in
            - Path=/sign-up
        - id: user
          uri: ${user.uri}
          predicates:
            - Path=/users/**, /user/**
sqids:
  alphabet: lHyvdsuj65rYFWpT2CBfRbUhKDGxJAzQaZ47XSc0VgPImtk8o3nwEq1NMe9OiL

whitelist:
  paths:
    - /sign-in
    - /sign-up