server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: ${account.uri}
          predicates:
            - Path=/**

hashids:
  salt: J5%pN84xi5MZ

whitelist:
  paths:
    - /login