server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${auth.uri}
          predicates:
            - Path=/login
        - id: account
          uri: ${account.uri}
          predicates:
            - Path=/users/**, /user/**
sqids:
  alphabet: lHyvdsuj65rYFWpT2CBfRbUhKDGxJAzQaZ47XSc0VgPImtk8o3nwEq1NMe9OiL

whitelist:
  paths:
    - /login