server:
  port: 9003
  shutdown: graceful
  servlet:
    context-path: /api

spring:
  config:
    import:
      - optional:classpath:application-base.yml
  application:
    name: console
  profiles:
    active: development

whitelist:
  paths:
    - /signin