spring:
  data:
    redis:
      port: 6379
      password: FlM34FN&peIc
      host: 127.0.0.1
      timeout: 30s

  datasource:
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: writer
      password: dbforstudy
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db_study
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: reader
      password: dbforstudy
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db_study
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  devtools:
    add-properties: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com.zaxxer.hikari: DEBUG
    web: DEBUG

sqids:
  alphabet: lHyvdsuj65rYFWpT2CBfRbUhKDGxJAzQaZ47XSc0VgPImtk8o3nwEq1NMe9OiL