= RESTful Fumble API Guide
Deppan;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview_http_verbs]]
== HTTP verbs

RESTful fumble tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview_http_status_codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[overview_errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object that describes the problem.
The error object has the following structure:

For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:

[[overview_hypermedia]]
== Hypermedia

RESTful Notes uses hypermedia and resources include links to other resources in their responses.
Responses are in https://github.com/mikekelly/hal_specification[Hypertext
Application Language (HAL)] format.
Links can be found beneath the `_links` key.
Users of the API should not create URIs themselves, instead they should use the above-described links to navigate from resource to resource.

[[resources]]
= Resources

[[resources_index]]
== Account

The parameter of

include::{snippets}/account/path-parameters.adoc[]

The response of fields

include::{snippets}/account/response-fields.adoc[]

The account provides the entry point into the service.

include::{snippets}/account/http-response.adoc[]

[[resources_index_access]]
=== Accessing the index

A `GET` request is used to access the index

operation::index-example[snippets='response-fields,http-response,links']

[[resources_notes]]
== Notes

The Notes resources is used to create and list notes

[[resources_notes_list]]
=== Listing notes

A `GET` request will list all of the service's notes.

operation::notes-list-example[snippets='response-fields,curl-request,http-response']

[[resources_notes_create]]
=== Creating a note

A `POST` request is used to create a note.

operation::notes-create-example[snippets='request-fields,curl-request,http-response']

[[resources_tags]]
== Tags

The Tags resource is used to create and list tags.

[[resources_tags_list]]
=== Listing tags

A `GET` request will list all of the service's tags.

operation::tags-list-example[snippets='response-fields,curl-request,http-response']

[[resources_tags_create]]
=== Creating a tag

A `POST` request is used to create a note

operation::tags-create-example[snippets='request-fields,curl-request,http-response']

